//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Subject { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
    
        public virtual PaperType PaperType { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
